version: '3'

services:
  machine1:
    image: ubuntu
    command: /code/prj2 -p 13337 -h /code/hostfile
    hostname: vdi-linux-030.ccs.neu.edu
    networks:
      lab1:
        aliases:
        - vdi-linux-030.ccs.neu.edu
    volumes:
    - "./:/code"


  machine2:
    image: ubuntu
    command:  /code/prj2 -p 13337 -h /code/hostfile -pause 5
    hostname: vdi-linux-031.ccs.neu.edu
    networks:
      lab1:
        aliases:
        - vdi-linux-031.ccs.neu.edu
    volumes:
    - "./:/code"


  machine3:
    image: ubuntu
    command: /code/prj2 -p 13337 -h /code/hostfile -pause 8
    hostname: vdi-linux-032.ccs.neu.edu
    networks:
      lab1:
        aliases:
        - vdi-linux-032.ccs.neu.edu
    volumes:
    - "./:/code"


  machine4:
    image: ubuntu
    command: /code/prj2 -p 13337 -h /code/hostfile -pause 10
    hostname: vdi-linux-033.ccs.neu.edu
    networks:
      lab1:
        aliases:
        - vdi-linux-033.ccs.neu.edu
    volumes:
    - "./:/code"

  machine5:
    image: ubuntu
    command: /code/prj2 -p 13337 -h /code/hostfile -pause 12
    hostname: vdi-linux-034.ccs.neu.edu
    networks:
      lab1:
        aliases:
        - vdi-linux-034.ccs.neu.edu
    volumes:
    - "./:/code"

networks:
  lab1:
    driver: bridge