version: '3'

services:
  machine1:
    image: ubuntu
    command: /code/prj2 -p 13337 -h /code/hostfile
    hostname: vdi-linux-030.ccs.neu.edu
    networks:
      lab1:
        aliases:
        - vdi-linux-030.ccs.neu.edu
    volumes:
    - "./:/code"


  machine2:
    image: ubuntu
    command:  /code/prj2 -p 13337 -h /code/hostfile -pause 2
    hostname: vdi-linux-031.ccs.neu.edu
    networks:
      lab1:
        aliases:
        - vdi-linux-031.ccs.neu.edu
    volumes:
    - "./:/code"


  machine3:
    image: ubuntu
    command: /code/prj2 -p 13337 -h /code/hostfile -pause 5
    hostname: vdi-linux-032.ccs.neu.edu
    networks:
      lab1:
        aliases:
        - vdi-linux-032.ccs.neu.edu
    volumes:
    - "./:/code"
#
#
#  machine4:
#    image: ubuntu
#    command: /code/prj2 -p 10 -h hostfile
#    hostname: vdi-linux-033.ccs.neu.edu
#    expose:
#    - "10000"
#    networks:
#      lab1:
#        aliases:
#        - vdi-linux-033.ccs.neu.edu
#    volumes:
#    - "./lab1:/code"


networks:
  lab1:
    driver: bridge